#!/bin/sh
#
# Launch weston in boot stage
#
case "$1" in
  start)
	printf "Starting weston: "
	chmod 0700 /dev/shm/
	export XDG_RUNTIME_DIR=/dev/shm
	export XDG_CONFIG_HOME=/etc/xdg
	weston --backend=drm-backend.so --tty=1 --idle-time=0 &
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  *)
	echo "Usage: $0 {start}"
	exit 1
esac

exit $?
